--------------------------------------------------------
--  파일이 생성됨 - 일요일-8월-25-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CUST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JANGAN"."CUST_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1021 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "JANGAN"."CUSTOMER" 
   (	"CUST_NO" NUMBER(4,0), 
	"CUST_NAME" VARCHAR2(20 BYTE), 
	"BUSINESS_LICENSE1" NUMBER(3,0), 
	"BUSINESS_LICENSE2" NUMBER(2,0), 
	"BUSINESS_LICENSE3" NUMBER(5,0), 
	"TRADE_REG_DATE" DATE DEFAULT sysdate, 
	"PHONE_NO1" NUMBER(3,0), 
	"PHONE_NO2" NUMBER(4,0), 
	"PHONE_NO3" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JANGAN_USER
--------------------------------------------------------

  CREATE TABLE "JANGAN"."JANGAN_USER" 
   (	"USER_ID" VARCHAR2(15 BYTE), 
	"USER_PW" VARCHAR2(15 BYTE), 
	"SUDO_GRADE" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MAT_CATEGORY
--------------------------------------------------------

  CREATE TABLE "JANGAN"."MAT_CATEGORY" 
   (	"CATE_NAME" VARCHAR2(10 BYTE), 
	"CATE_NO" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MAT_INFO
--------------------------------------------------------

  CREATE TABLE "JANGAN"."MAT_INFO" 
   (	"CATE_NO" NUMBER(4,0), 
	"OTHER_TYPE" VARCHAR2(50 BYTE), 
	"SIZE1" NUMBER(10,0), 
	"SIZE2" NUMBER(10,0), 
	"SIZE3" NUMBER(10,0), 
	"QUANTITY" NUMBER(4,0), 
	"UNIT_PRICE" NUMBER(10,0), 
	"UNIT_SET" NUMBER(10,0) DEFAULT 1, 
	"RECEIVE_DATE" DATE DEFAULT sysdate, 
	"CUST_NO" NUMBER(4,0), 
	"ITEM_SERIAL" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUDO
--------------------------------------------------------

  CREATE TABLE "JANGAN"."SUDO" 
   (	"SUDO_NAME" VARCHAR2(10 BYTE), 
	"SUDO_GRADE" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UNIT_SET
--------------------------------------------------------

  CREATE TABLE "JANGAN"."UNIT_SET" 
   (	"UNIT_SET" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JANGAN.CUSTOMER
SET DEFINE OFF;
Insert into JANGAN.CUSTOMER (CUST_NO,CUST_NAME,BUSINESS_LICENSE1,BUSINESS_LICENSE2,BUSINESS_LICENSE3,TRADE_REG_DATE,PHONE_NO1,PHONE_NO2,PHONE_NO3) values (1001,'미래합판',null,null,null,to_date('2019-03-12','RRRR-MM-DD'),null,null,null);
Insert into JANGAN.CUSTOMER (CUST_NO,CUST_NAME,BUSINESS_LICENSE1,BUSINESS_LICENSE2,BUSINESS_LICENSE3,TRADE_REG_DATE,PHONE_NO1,PHONE_NO2,PHONE_NO3) values (1002,'현대씽크',null,null,null,to_date('2019-03-12','RRRR-MM-DD'),null,null,null);
Insert into JANGAN.CUSTOMER (CUST_NO,CUST_NAME,BUSINESS_LICENSE1,BUSINESS_LICENSE2,BUSINESS_LICENSE3,TRADE_REG_DATE,PHONE_NO1,PHONE_NO2,PHONE_NO3) values (1003,'울산산업',0,0,0,to_date('2018-09-07','RRRR-MM-DD'),0,0,0);
Insert into JANGAN.CUSTOMER (CUST_NO,CUST_NAME,BUSINESS_LICENSE1,BUSINESS_LICENSE2,BUSINESS_LICENSE3,TRADE_REG_DATE,PHONE_NO1,PHONE_NO2,PHONE_NO3) values (1005,'미래산업',0,0,0,to_date('2019-01-21','RRRR-MM-DD'),0,0,0);
Insert into JANGAN.CUSTOMER (CUST_NO,CUST_NAME,BUSINESS_LICENSE1,BUSINESS_LICENSE2,BUSINESS_LICENSE3,TRADE_REG_DATE,PHONE_NO1,PHONE_NO2,PHONE_NO3) values (1006,'포항스틸',0,0,0,to_date('2017-06-14','RRRR-MM-DD'),0,0,0);
Insert into JANGAN.CUSTOMER (CUST_NO,CUST_NAME,BUSINESS_LICENSE1,BUSINESS_LICENSE2,BUSINESS_LICENSE3,TRADE_REG_DATE,PHONE_NO1,PHONE_NO2,PHONE_NO3) values (1007,'KH세무',0,0,0,to_date('2017-12-07','RRRR-MM-DD'),0,0,0);
Insert into JANGAN.CUSTOMER (CUST_NO,CUST_NAME,BUSINESS_LICENSE1,BUSINESS_LICENSE2,BUSINESS_LICENSE3,TRADE_REG_DATE,PHONE_NO1,PHONE_NO2,PHONE_NO3) values (1004,'경주기계',555,22,33333,to_date('2016-08-14','RRRR-MM-DD'),10,3333,2222);
Insert into JANGAN.CUSTOMER (CUST_NO,CUST_NAME,BUSINESS_LICENSE1,BUSINESS_LICENSE2,BUSINESS_LICENSE3,TRADE_REG_DATE,PHONE_NO1,PHONE_NO2,PHONE_NO3) values (1008,'울산테크',0,0,0,to_date('2018-11-15','RRRR-MM-DD'),0,0,0);
REM INSERTING into JANGAN.JANGAN_USER
SET DEFINE OFF;
Insert into JANGAN.JANGAN_USER (USER_ID,USER_PW,SUDO_GRADE) values ('admin','1234',0);
Insert into JANGAN.JANGAN_USER (USER_ID,USER_PW,SUDO_GRADE) values ('java','1234',1);
Insert into JANGAN.JANGAN_USER (USER_ID,USER_PW,SUDO_GRADE) values ('jangan','1234',1);
REM INSERTING into JANGAN.MAT_CATEGORY
SET DEFINE OFF;
Insert into JANGAN.MAT_CATEGORY (CATE_NAME,CATE_NO) values ('기타',0);
Insert into JANGAN.MAT_CATEGORY (CATE_NAME,CATE_NO) values ('합판',10);
Insert into JANGAN.MAT_CATEGORY (CATE_NAME,CATE_NO) values ('씽크',20);
Insert into JANGAN.MAT_CATEGORY (CATE_NAME,CATE_NO) values ('피스',30);
REM INSERTING into JANGAN.MAT_INFO
SET DEFINE OFF;
Insert into JANGAN.MAT_INFO (CATE_NO,OTHER_TYPE,SIZE1,SIZE2,SIZE3,QUANTITY,UNIT_PRICE,UNIT_SET,RECEIVE_DATE,CUST_NO,ITEM_SERIAL) values (20,'B-101 원터치',2200,600,0,2,82000,1,to_date('2019-02-14','RRRR-MM-DD'),1002,1902141002001);
Insert into JANGAN.MAT_INFO (CATE_NO,OTHER_TYPE,SIZE1,SIZE2,SIZE3,QUANTITY,UNIT_PRICE,UNIT_SET,RECEIVE_DATE,CUST_NO,ITEM_SERIAL) values (20,'G',620,600,0,1,22000,1,to_date('2019-02-14','RRRR-MM-DD'),1002,1902141002003);
Insert into JANGAN.MAT_INFO (CATE_NO,OTHER_TYPE,SIZE1,SIZE2,SIZE3,QUANTITY,UNIT_PRICE,UNIT_SET,RECEIVE_DATE,CUST_NO,ITEM_SERIAL) values (20,'보조대',0,3150,100,1,26000,1,to_date('2019-02-14','RRRR-MM-DD'),1002,1902141002002);
Insert into JANGAN.MAT_INFO (CATE_NO,OTHER_TYPE,SIZE1,SIZE2,SIZE3,QUANTITY,UNIT_PRICE,UNIT_SET,RECEIVE_DATE,CUST_NO,ITEM_SERIAL) values (20,'SS배수구',0,0,0,3,5000,1,to_date('2019-02-12','RRRR-MM-DD'),1002,1902121002001);
Insert into JANGAN.MAT_INFO (CATE_NO,OTHER_TYPE,SIZE1,SIZE2,SIZE3,QUANTITY,UNIT_PRICE,UNIT_SET,RECEIVE_DATE,CUST_NO,ITEM_SERIAL) values (10,'하이그로시 백색펄',1220,2440,15,0,31500,1,to_date('2019-02-14','RRRR-MM-DD'),1001,1902141001001);
Insert into JANGAN.MAT_INFO (CATE_NO,OTHER_TYPE,SIZE1,SIZE2,SIZE3,QUANTITY,UNIT_PRICE,UNIT_SET,RECEIVE_DATE,CUST_NO,ITEM_SERIAL) values (10,'MDF 밤색골드티크웨이브',1220,2440,18,1,50000,1,to_date('2019-02-18','RRRR-MM-DD'),1001,1902181001001);
Insert into JANGAN.MAT_INFO (CATE_NO,OTHER_TYPE,SIZE1,SIZE2,SIZE3,QUANTITY,UNIT_PRICE,UNIT_SET,RECEIVE_DATE,CUST_NO,ITEM_SERIAL) values (10,'MDF 백색골드티크웨이브',1220,2440,18,1,50000,1,to_date('2019-02-18','RRRR-MM-DD'),1001,1902181001002);
REM INSERTING into JANGAN.SUDO
SET DEFINE OFF;
Insert into JANGAN.SUDO (SUDO_NAME,SUDO_GRADE) values ('MASTER',0);
Insert into JANGAN.SUDO (SUDO_NAME,SUDO_GRADE) values ('OWNER',1);
REM INSERTING into JANGAN.UNIT_SET
SET DEFINE OFF;
Insert into JANGAN.UNIT_SET (UNIT_SET) values (1);
Insert into JANGAN.UNIT_SET (UNIT_SET) values (5);
Insert into JANGAN.UNIT_SET (UNIT_SET) values (10);
Insert into JANGAN.UNIT_SET (UNIT_SET) values (50);
Insert into JANGAN.UNIT_SET (UNIT_SET) values (100);
Insert into JANGAN.UNIT_SET (UNIT_SET) values (500);
Insert into JANGAN.UNIT_SET (UNIT_SET) values (1000);
--------------------------------------------------------
--  DDL for Index PK_CUSTOMER
--------------------------------------------------------

  CREATE UNIQUE INDEX "JANGAN"."PK_CUSTOMER" ON "JANGAN"."CUSTOMER" ("CUST_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ITEM_SERIAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "JANGAN"."PK_ITEM_SERIAL" ON "JANGAN"."MAT_INFO" ("ITEM_SERIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "JANGAN"."PK_USER" ON "JANGAN"."JANGAN_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007015
--------------------------------------------------------

  CREATE UNIQUE INDEX "JANGAN"."SYS_C007015" ON "JANGAN"."MAT_CATEGORY" ("CATE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007016
--------------------------------------------------------

  CREATE UNIQUE INDEX "JANGAN"."SYS_C007016" ON "JANGAN"."MAT_CATEGORY" ("CATE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007017
--------------------------------------------------------

  CREATE UNIQUE INDEX "JANGAN"."SYS_C007017" ON "JANGAN"."SUDO" ("SUDO_GRADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007018
--------------------------------------------------------

  CREATE UNIQUE INDEX "JANGAN"."SYS_C007018" ON "JANGAN"."SUDO" ("SUDO_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007036
--------------------------------------------------------

  CREATE UNIQUE INDEX "JANGAN"."SYS_C007036" ON "JANGAN"."UNIT_SET" ("UNIT_SET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "JANGAN"."CUSTOMER" ADD CONSTRAINT "PK_CUSTOMER" PRIMARY KEY ("CUST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JANGAN"."CUSTOMER" MODIFY ("CUST_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JANGAN_USER
--------------------------------------------------------

  ALTER TABLE "JANGAN"."JANGAN_USER" ADD CONSTRAINT "PK_USER" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JANGAN"."JANGAN_USER" MODIFY ("USER_PW" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MAT_CATEGORY
--------------------------------------------------------

  ALTER TABLE "JANGAN"."MAT_CATEGORY" ADD UNIQUE ("CATE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JANGAN"."MAT_CATEGORY" ADD PRIMARY KEY ("CATE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MAT_INFO
--------------------------------------------------------

  ALTER TABLE "JANGAN"."MAT_INFO" ADD CONSTRAINT "C_ITEM_SERIAL" CHECK (item_serial>=1000000000000) ENABLE;
  ALTER TABLE "JANGAN"."MAT_INFO" ADD CONSTRAINT "PK_ITEM_SERIAL" PRIMARY KEY ("ITEM_SERIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JANGAN"."MAT_INFO" MODIFY ("UNIT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "JANGAN"."MAT_INFO" MODIFY ("QUANTITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUDO
--------------------------------------------------------

  ALTER TABLE "JANGAN"."SUDO" ADD UNIQUE ("SUDO_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JANGAN"."SUDO" ADD PRIMARY KEY ("SUDO_GRADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UNIT_SET
--------------------------------------------------------

  ALTER TABLE "JANGAN"."UNIT_SET" ADD PRIMARY KEY ("UNIT_SET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JANGAN_USER
--------------------------------------------------------

  ALTER TABLE "JANGAN"."JANGAN_USER" ADD CONSTRAINT "FK_SUDO" FOREIGN KEY ("SUDO_GRADE")
	  REFERENCES "JANGAN"."SUDO" ("SUDO_GRADE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAT_INFO
--------------------------------------------------------

  ALTER TABLE "JANGAN"."MAT_INFO" ADD CONSTRAINT "FK_CATE" FOREIGN KEY ("CATE_NO")
	  REFERENCES "JANGAN"."MAT_CATEGORY" ("CATE_NO") ENABLE;
  ALTER TABLE "JANGAN"."MAT_INFO" ADD CONSTRAINT "FK_CUST" FOREIGN KEY ("CUST_NO")
	  REFERENCES "JANGAN"."CUSTOMER" ("CUST_NO") ENABLE;
  ALTER TABLE "JANGAN"."MAT_INFO" ADD CONSTRAINT "FK_UNIT_SET" FOREIGN KEY ("UNIT_SET")
	  REFERENCES "JANGAN"."UNIT_SET" ("UNIT_SET") ENABLE;
